services:
  database:
    image: postgres
    container_name: ${DATABASE_HOST}
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    command: postgres -p ${DATABASE_PORT}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./database/postgresql-docker-image/database_data:/var/lib/postgresql/data
      - ./database/postgresql-docker-image/create_tables.sql:/docker-entrypoint-initdb.d/1-create_tables.sql:ro
      - ./database/postgresql-docker-image/fill_tables.sql:/docker-entrypoint-initdb.d/2-fill_tables.sql:ro
      - ./database/postgresql-docker-image/generated_data:/generated_data
      - ./database/postgresql-docker-image/specialties.txt:/specialties.txt
